version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  ganache:
    image: trufflesuite/ganache-cli
    command: ["ganache-cli", "-m", "weapon pioneer idle rotate lady year blossom pass tilt ignore tourist waste oblige nose walk"]
    ports:
      - "8545:8545"
